# Generated by Django 5.0a1 on 2023-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='timestamp',
        ),
    ]
