# Generated by Django 5.0a1 on 2023-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0002_remove_sales_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
