version: '0.5'

services:
  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    networks:
      - frame

  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    networks:
      - frame

    depends_on:
      backend:
        condition: service_started

networks:
  frame:
    driver: bridge